service: swagger-sls

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2

plugins:
  - serverless-offline

functions:
  api:
    handler: handler.api
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{any+}
          method: ANY
          cors: true

